routes/web.php
<?php
use App\Artigo;
use \App\Http\Controllers\Admin\ArtigosController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $req) {

    if(isset($req->busca) && $req->busca != ""){
        $busca = $req->busca;
        $lista = ArtigosController::listaArtigosSite(3,$busca);

      // busca
    }else{
        $lista = ArtigosController::listaArtigosSite(3);
        $busca = "";
    }

    return view('site',compact('lista','busca'));
})->name('site');


Route::get('/artigo/{id}/{titulo?}', function ($id) {
    $artigo = Artigo::find($id);
    if($artigo){
        return view('artigo', compact('artigo'));
    }
    return redirect()->route('site');
    
})->name('artigo');

Route::get('/admin/qr-code/{id}', function ($id) {
    return QrCode::size(500)->generate($id);
})->name('qr');

Route::get('/uploadfile', 'UploadfileController@index');
Route::post('/uploadfile', 'UploadfileController@upload');

Route::get('multiple-file-upload', 'MultipleUploadController@index');

Route::post('multiple-file-upload/upload', 'MultipleUploadController@upload')->name('upload');

Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin');

Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('artigos', 'ArtigosController')->middleware('can:autor');
    Route::resource('pontos', 'PontosController');
    Route::resource('usuarios', 'UsuariosController')->middleware('can:eAdmin');
    Route::resource('autores', 'AutoresController')->middleware('can:eAdmin');
    Route::resource('adm', 'AdminController')->middleware('can:eAdmin');
});

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')
<pagina-component tamanho="10">

    <painel-component titulo= "Dashboard">
        <migalhas-component v-bind:lista="{{$listaMigalhas}}"></migalhas-component>
        <div class="row">

            <div class="col-md-4">

                <caixa-component
                        qtd="{{$totalPontos}}"
                        titulo="Pontos"
                        url="{{route('pontos.index')}}"
                        cor="green"
                        icone="ion-home">
                </caixa-component>
            </div>

            @can('autor')
                <div class="col-md-4">
                
                    <caixa-component 
                    qtd="{{$totalArtigos}}"
                    titulo="Artigos"
                    url="{{route('artigos.index')}}"
                    cor="orange"
                    icone="ion ion-pie-graph">
                    </caixa-component>
                </div>
            @endcan
                
            @can('eAdmin')
                
                <div class="col-md-4">
                    
                    <caixa-component 
                    qtd="{{$totalUsuarios}}"
                    titulo="Usuários"
                    url="{{route('usuarios.index')}}"
                    cor="blue"
                    icone="ion ion-person-stalker">
                    </caixa-component>
    
                </div>
                
                <div class="col-md-4">
                    
                    <caixa-component 
                    qtd="{{$totalAutores}}"
                    titulo="Autores"
                    url="{{route('autores.index')}}"
                    cor="red"
                    icone="ion ion-person">
                    </caixa-component>
    
                </div>
    
                <div class="col-md-4">
                    
                    <caixa-component 
                    qtd="{{$totalAdmin}}"
                    titulo="Admins"
                    url="{{route('adm.index')}}"
                    cor="green"
                    icone="ion ion-person">
                    </caixa-component>
    
                </div>
            @endcan
                
        </div>

    </painel-component>

</pagina-component>
@endsection

resources/views/artigo.blade.php
@extends('layouts.app')

@section('content')
    <pagina-component tamanho="12">
        <painel-component >
            <h2 class="text-center">{{$artigo->titulo}}</h2>
            <h4 class="text-center">{{$artigo->descricao}}</h4>
            <p>
                {!!$artigo->conteudo!!}
            </p>

            <p class="text-center"><small>Por: {{$artigo->user->name}} - {{date('d/m/Y', strtotime($artigo->data))}}</small></p>
        </painel-component>
    </pagina-component>
@endsection

resources/views/multiple_file_upload.blade.php
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laravel 5.8 - Multiple File Upload with Progressbar using Ajax jQuery</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>
</head>
<body>
<div class="container">
    <br />
    <h3 align="center">Teste de Upload de múltiplas imagens</h3>
    <br />
    <h4><a href="/">Voltar</a> <br></h4>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Upload</h3>
        </div>
        <div class="panel-body">
            <br />
            <form method="post" action="{{ route('upload') }}" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-md-3" align="right"><h4>Selecione as imagens</h4></div>
                    <div class="col-md-6">
                        <input type="file" name="file[]" id="file" accept="image/*" multiple />
                    </div>
                    <div class="col-md-3">

                        <input type="submit" name="upload" value="Enviar" class="btn btn-success" />
                    </div>
                </div>
            </form>
            <br />
            <div class="progress">
                <div class="progress-bar" aria-valuenow="" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                    0%
                </div>
            </div>
            <br />
            <div id="success" class="row">

            </div>
            <br />
        </div>
    </div>
</div>
</body>
</html>

<script>
    $(document).ready(function(){
        $('form').ajaxForm({
            beforeSend:function(){
                $('#success').empty();
                $('.progress-bar').text('0%');
                $('.progress-bar').css('width', '0%');
            },
            uploadProgress:function(event, position, total, percentComplete){
                $('.progress-bar').text(percentComplete + '0%');
                $('.progress-bar').css('width', percentComplete + '0%');
            },
            success:function(data)
            {
                if(data.success)
                {
                    $('#success').html('<div class="text-success text-center"><b>'+data.success+'</b></div><br /><br />');
                    $('#success').append(data.image);
                    $('.progress-bar').text('Concluido!');
                    $('.progress-bar').css('width', '100%');
                }
            }
        });
    });
</script>

<script>
    $(document).ready(function() {

        $('#imageFile').change(function(evt) {

            var files = evt.target.files;
            var file = files[0];

            if (file) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('preview').src = e.target.result;
                };
                reader.readAsDataURL(file);
            }
        });
    });

    function ResizeImage() {
        if (window.File && window.FileReader && window.FileList && window.Blob) {
            var filesToUploads = document.getElementById('imageFile').files;
            var file = filesToUploads[0];
            if (file) {

                var reader = new FileReader();
                // Set the image once loaded into file reader
                reader.onload = function(e) {

                    var img = document.createElement("img");
                    img.src = e.target.result;

                    var canvas = document.createElement("canvas");
                    var ctx = canvas.getContext("2d");
                    ctx.drawImage(img, 0, 0);

                    var MAX_WIDTH = 400;
                    var MAX_HEIGHT = 400;
                    var width = img.width;
                    var height = img.height;

                    if (width > height) {
                        if (width > MAX_WIDTH) {
                            height *= MAX_WIDTH / width;
                            width = MAX_WIDTH;
                        }
                    } else {
                        if (height > MAX_HEIGHT) {
                            width *= MAX_HEIGHT / height;
                            height = MAX_HEIGHT;
                        }
                    }
                    canvas.width = width;
                    canvas.height = height;
                    var ctx = canvas.getContext("2d");
                    ctx.drawImage(img, 0, 0, width, height);

                    dataurl = canvas.toDataURL(file.type);
                    document.getElementById('output').src = dataurl;
                }
                reader.readAsDataURL(file);

            }

        } else {
            alert('The File APIs are not fully supported in this browser.');
        }
    }
</script>

resources/views/qrcode.blade.php
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

<div class="visible-print text-center">
    <h1>Laravel 5.7 - QR Code Generator Example</h1>

    {!! QrCode::size(250)->generate('ItSolutionStuff.com'); !!}

    <p>example by ItSolutionStuf.com.</p>
</div>

</body>
</html>

resources/views/site.blade.php
@extends('layouts.app')

@section('content')
    <pagina-component tamanho="12">
        <painel-component titulo="Artigos">

            <a href="admin/pontos">Bater Ponto</a> <br>
            <a href="multiple-file-upload">[TESTE] Upload de múltiplas imagens</a>
            <div class="row h-100 justify-content-center align-items-center">
                <p>
                    <form class="form-inline text-center" action="{{route('site')}}" method="get" >
                        <input type="search" class="form-control" name="busca" placeholder="Buscar" value="{{isset($busca) ? $busca : ""}}">
                        <button class="btn btn-info">Buscar</button>
                    </form>
                </p>
                
            </div>
            <p></p>

            <qr-stream> </qr-stream>

            <div class="card-deck">

                @foreach ($lista as $key => $value)
                    <card-artigo-component
                    titulo="{{str_limit($value->titulo, 30, "...")}}"
                    descricao="{{str_limit($value->descricao, 30, "...")}}"
                    link="{{route('artigo', [$value->id, str_slug($value->titulo)])}}"
                    imagem="https://as2.ftcdn.net/jpg/02/23/40/63/500_F_223406364_uyK6rtziI4CPAV7tfsqiPcVuKj9La7zL.jpg"
                    data="{{$value->data}}"
                    autor="{{$value->autor}}"
                    sm="6"
                    md="4"
                    >
                    </card-artigo-component>
                @endforeach
                
            </div>
            <div class="row h-100 justify-content-center align-items-center">
                    {{$lista->links()}}
            </div>


            
        </painel-component>
    </pagina-component>
@endsection

<script>
    import QrDetect from "../js/components/QrDetect";
    export default {
        components: {QrDetect}
    }
</script>
<script>
    import QrDetect from "../js/components/QrDetect";
    export default {
        components: {QrDetect}
    }
</script>
<script>
    import QrDetect from "../js/components/QrDetect";
    export default {
        components: {QrDetect}
    }
</script>
<script>
    import QrStream from "../js/components/QrStream";
    export default {
        components: {QrStream}
    }
</script>

resources/views/upload.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>File Uploading in Laravel</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<br />

<div class="container">
    <h3 align="center">File Uploading in Laravel</h3>
    <br />
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            Upload Validation Error<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ $message }}</strong>
        </div>
        <img src="/images/{{ Session::get('path') }}" width="300" />
    @endif
    <form method="post" action="{{url('/uploadfile')}}" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="form-group">
            <table class="table">
                <tr>
                    <td width="40%" align="right"><label>Select File for Upload</label></td>
                    <td width="30"><input type="file" name="file[]" multiple/></td>
                    <td width="30%" align="left"><input type="submit" name="upload" class="btn btn-primary" value="Upload"></td>
                </tr>
                <tr>
                    <td width="40%" align="right"></td>
                    <td width="30"><span class="text-muted">jpg, png, gif</span></td>
                    <td width="30%" align="left"></td>
                </tr>
            </table>
        </div>
    </form>
    <br />
</div>
</body>
</html>