routes/web.php
<?php
use App\Artigo;
use \App\Http\Controllers\Admin\ArtigosController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $req) {

    if(isset($req->busca) && $req->busca != ""){
        $busca = $req->busca;
        $lista = ArtigosController::listaArtigosSite(3,$busca);

      // busca
    }else{
        $lista = ArtigosController::listaArtigosSite(3);
        $busca = "";
    }

    return view('site',compact('lista','busca'));
})->name('site');


Route::get('/artigo/{id}/{titulo?}', function ($id) {
    $artigo = Artigo::find($id);
    if($artigo){
        return view('artigo', compact('artigo'));
    }
    return redirect()->route('site');
    
})->name('artigo');

Route::get('/admin/qr-code/{id}', function ($id) {
    return QrCode::size(500)->generate($id);
})->name('qr');

Route::get('/uploadfile', 'UploadfileController@index');
Route::post('/uploadfile', 'UploadfileController@upload');

Route::get('multiple-file-upload', 'MultipleUploadController@index');

Route::post('multiple-file-upload/upload', 'MultipleUploadController@upload')->name('upload');

Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin');

Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('artigos', 'ArtigosController')->middleware('can:autor');
    Route::resource('pontos', 'PontosController');
    Route::resource('usuarios', 'UsuariosController')->middleware('can:eAdmin');
    Route::resource('autores', 'AutoresController')->middleware('can:eAdmin');
    Route::resource('adm', 'AdminController')->middleware('can:eAdmin');
});

app/Artigo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Artigo extends Model
{
    use SoftDeletes;

    protected $fillable = ['titulo','descricao','conteudo','data'];

    protected $dates = ['deleted_at'];

    public function user(){
        return $this->belongsTo('App\User');
    }

}

app/Http/Controllers/Admin/ArtigosController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Artigo;
use Illuminate\Support\Facades\DB;

class ArtigosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listaMigalhas = json_encode([
            ["titulo"=>"Admin","url"=>route('admin')],
            ["titulo"=>"Lista de artigos","url"=>""]
        ]);
        //PRIMEIRA OPÇÂO
        /*$listaArtigos = Artigo::select('id','titulo','descricao','user_id', 'data')->paginate(5);
        
        foreach($listaArtigos as $key => $value){
            $value->user_id = \App\User::find($value->user_id)->name; //primeira saida

        }
        
        $listaArtigos = DB::table('artigos')
                        ->join('users', 'users.id', '=', 'artigos.user_id')
                        ->select('artigos.id','artigos.titulo','artigos.descricao','users.name', 'artigos.data')
                        ->whereNull('deleted_at')
                        ->paginate(5);

                        */



        $listaArtigos = ArtigosController::listaArtigos(5);

        return view('admin.artigos.index',compact('listaMigalhas','listaArtigos'));
    }

    public static function listaArtigos($paginate){
        /*
        $listaArtigos = Artigo::select('id','titulo','descricao','user_id', 'data')->paginate($paginate);

        foreach($listaArtigos as $key => $value){
            $value->user_id = User::find($value->user_id)->name; //primeira saida

        }

        */
        $user = auth()->user();

        if($user->admin == "S"){
            $listaArtigos = DB::table('artigos')
                ->join('users', 'users.id', '=', 'artigos.user_id')
                ->select('artigos.id','artigos.titulo','artigos.descricao','users.name', 'artigos.data')
                ->whereNull('deleted_at')
                ->paginate($paginate);
        } else {
            $listaArtigos = DB::table('artigos')
                ->join('users', 'users.id', '=', 'artigos.user_id')
                ->select('artigos.id','artigos.titulo','artigos.descricao','users.name', 'artigos.data')
                ->whereNull('deleted_at')
                ->where('artigos.user_id', '=', $user->id)
                ->paginate($paginate);


        }

        return $listaArtigos;
    }

    public static function listaArtigosSite($paginate, $busca = null){

        if($busca){
            $listaArtigos = DB::table('artigos')
                ->join('users','users.id','=','artigos.user_id')
                ->select('artigos.id','artigos.titulo','artigos.descricao','users.name as autor','artigos.data')
                ->whereNull('deleted_at')
                ->whereDate('data','<=',date('Y-m-d'))
                ->where(function($query) use ($busca){
                    $query->orWhere('titulo','like','%'.$busca.'%')
                        ->orWhere('descricao','like','%'.$busca.'%');
                })
                ->orderBy('data','DESC')
                ->paginate($paginate);
        } else {
            $listaArtigos = DB::table('artigos')
                ->join('users', 'users.id', '=', 'artigos.user_id')
                ->select('artigos.id','artigos.titulo','artigos.descricao','users.name as autor', 'artigos.data')
                ->whereNull('deleted_at')
                ->whereDate('data', '<=',date('Y-m-d'))
                ->orderBy('data', 'DESC')
                ->paginate($paginate);

        }

        return $listaArtigos;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data = $request->all();

        $validacao = \Validator::make($data, [
            "titulo" => "required",
            "descricao" => "required",
            "conteudo" => "required",
            "data" => "required",
        ]);

        if($validacao->fails()){
            return redirect()->back()->withErrors($validacao)->withInput();
        }
        
        $user = auth()->user();
        $user->artigos()->create($data);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return Artigo::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $validacao = \Validator::make($data, [
            "titulo" => "required",
            "descricao" => "required",
            "conteudo" => "required",
            "data" => "required",
        ]);

        if($validacao->fails()){
            return redirect()->back()->withErrors($validacao)->withInput();
        }
        

        $user = auth()->user();
        $user->artigos()->find($id)->update($data);
        
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Artigo::find($id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/artigos/index.blade.php
@extends('layouts.app')

@section('content')
<pagina-component tamanho="10">

    @if($errors->all())
    <div class="alert alert-danger alert-dismissible text-center" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
      @foreach ($errors->all() as $key =>  $value)
        <li><strong>{{$value}}</strong></li>
      @endforeach
    </div>
    @endif

    <painel-component titulo= "Lista de Artigos">

        <migalhas-component v-bind:lista="{{$listaMigalhas}}"></migalhas-component>


        <tabela-lista-component 
        v-bind:titulos="['#','Título','Descrição','Autor', 'data']"
        v-bind:itens="{{json_encode($listaArtigos)}}"
        ordem="desc" ordemcol="0"
        criar="#criar" detalhe="/admin/artigos/" editar="/admin/artigos/" deletar="/admin/artigos/" token="{{ csrf_token() }}"
        modal="sim">
        </tabela-lista-component>

        <div class="row h-100 justify-content-center align-items-center">
          {{$listaArtigos->links()}}
        </div>
    </painel-component>

</pagina-component>

<modal-component nome="adicionar" titulo="Adicionar">
<formulario-component id="formAdicionar" css="" action="{{route('artigos.store')}}" method="post" enctype="" token="{{ csrf_token() }}">
    
      <div class="form-group">
        <label for="titulo">Título</label>
        <input type="text" class="form-control" id="titulo" name="titulo" placeholder="Título" value="{{old('titulo')}}">
      </div>
      <div class="form-group">
        <label for="descricao">Descrição</label>
        <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Descrição" value="{{old('descricao')}}">
      </div>

      <div class="form-group">
        <label for="addConteudo">Conteúdo</label>
        <ckeditor-component
          id="addConteudo"
          name="conteudo"
          value="{{old('conteudo')}}" 
          v-bind:config="{
            toolbar: [
              [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript' ]
            ],
            height: 200}" 
          >
        </ckeditor-component>

      </div>

      <div class="form-group">
        <label for="data">Data</label>
        <input type="date" class="form-control" id="data" name="data" value="{{old('data')}}">
      </div>
    
  </formulario-component>
  <span slot="botoes">
    <button form="formAdicionar" class="btn btn-info">Adicionar</button>
  </span>
</modal-component>

<modal-component nome="editar" titulo="Editar">
  <formulario-component id="formEditar" v-bind:action="'/admin/artigos/' + $store.state.item.id" method="put" enctype="" token="{{ csrf_token() }}">
    
    <div class="form-group">
      <label for="titulo">Título</label>
      <input type="text" class="form-control" id="titulo" name="titulo" v-model="$store.state.item.titulo" placeholder="Título">
    </div>
    <div class="form-group">
      <label for="descricao">Descrição</label>
      <input type="text" class="form-control" id="descricao" name="descricao" v-model="$store.state.item.descricao" placeholder="Descrição">
    </div>
    <div class="form-group">
      <label for="editConteudo">Conteúdo</label>
      
      <ckeditor-component
          id="editConteudo"
          name="conteudo"
          v-model="$store.state.item.conteudo" 
          v-bind:config="{
            toolbar: [
              [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript' ]
            ],
            height: 200}" 
          >
      </ckeditor-component>
    </div>

    <div class="form-group">
      <label for="data">Data</label>
      <input type="date" class="form-control" id="data" name="data" v-model="$store.state.item.data">
    </div>
  </formulario-component>
  <span slot="botoes">
    <button form="formEditar" class="btn btn-info">Salvar</button>
  </span>
</modal-component>

<modal-component nome="detalhe" v-bind:titulo="$store.state.item.titulo">
  <p>@{{$store.state.item.descricao}}</p>
  <p>@{{$store.state.item.conteudo}}</p>
</modal-component>
@endsection